[2025-03-04T12:27:32.463-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:32.508-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-04T12:27:32.528-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-04T12:27:32.529-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:32.570-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-28 00:00:00+00:00
[2025-03-04T12:27:32.587-0600] {standard_task_runner.py:72} INFO - Started process 19761 to run task
[2025-03-04T12:27:32.618-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpsaewb7n4']
[2025-03-04T12:27:32.623-0600] {standard_task_runner.py:105} INFO - Job 24: Subtask SendMessage
[2025-03-04T12:27:32.740-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-28T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:33.310-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-03-04T12:27:33.318-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:45.014-0600] {job.py:229} INFO - Heartbeat recovered after 52.13 seconds
[2025-03-04T12:29:05.375-0600] {job.py:229} INFO - Heartbeat recovered after 35.36 seconds
[2025-03-04T12:30:22.060-0600] {job.py:229} INFO - Heartbeat recovered after 16.34 seconds
[2025-03-04T12:32:12.042-0600] {job.py:229} INFO - Heartbeat recovered after 118.64 seconds
[2025-03-04T12:32:33.946-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:34.188-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:34.192-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-28T00:00:00+00:00, execution_date=20250228T000000, start_date=20250304T182732, end_date=20250304T183234
[2025-03-04T12:32:34.323-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:34.391-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:34.394-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
