[2025-03-04T12:27:26.375-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:26.503-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.542-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.546-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:26.723-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-25 00:00:00+00:00
[2025-03-04T12:27:26.733-0600] {standard_task_runner.py:72} INFO - Started process 19655 to run task
[2025-03-04T12:27:26.751-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmptj21x0ii']
[2025-03-04T12:27:26.761-0600] {standard_task_runner.py:105} INFO - Job 5: Subtask SendMessage
[2025-03-04T12:27:27.422-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-25T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:28.813-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-03-04T12:27:28.815-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:47.643-0600] {job.py:229} INFO - Heartbeat recovered after 50.25 seconds
[2025-03-04T12:29:13.605-0600] {job.py:229} INFO - Heartbeat recovered after 31.38 seconds
[2025-03-04T12:30:22.060-0600] {job.py:229} INFO - Heartbeat recovered after 16.35 seconds
[2025-03-04T12:32:16.701-0600] {job.py:229} INFO - Heartbeat recovered after 123.30 seconds
[2025-03-04T12:32:29.074-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:30.334-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:30.345-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-25T00:00:00+00:00, execution_date=20250225T000000, start_date=20250304T182726, end_date=20250304T183230
[2025-03-04T12:32:30.800-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:30.962-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:30.969-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
