[2025-03-04T12:46:42.578-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:46:42.626-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-04T18:46:35.938921+00:00 [queued]>
[2025-03-04T12:46:42.649-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-04T18:46:35.938921+00:00 [queued]>
[2025-03-04T12:46:42.649-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:46:42.687-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): StoreData> on 2025-03-04 18:46:35.938921+00:00
[2025-03-04T12:46:42.697-0600] {standard_task_runner.py:72} INFO - Started process 30058 to run task
[2025-03-04T12:46:42.703-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'StoreData', 'manual__2025-03-04T18:46:35.938921+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpgq6riium']
[2025-03-04T12:46:42.707-0600] {standard_task_runner.py:105} INFO - Job 35: Subtask StoreData
[2025-03-04T12:46:42.802-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.StoreData manual__2025-03-04T18:46:35.938921+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:46:42.988-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='StoreData' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T18:46:35.938921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-04T18:46:35.938921+00:00'
[2025-03-04T12:46:42.990-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:46:43.055-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-04T12:46:43.055-0600] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-04T12:46:43.056-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-04T12:46:43.057-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-04T12:46:43.058-0600] {__init__.py:150} INFO - plugin_name: mysql_native_password
[2025-03-04T12:46:43.060-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
[2025-03-04T12:46:43.160-0600] {dataEngineering.py:61} INFO - Data stored succesfully!
[2025-03-04T12:46:43.172-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-03-04T12:46:43.186-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:46:43.187-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=StoreData, run_id=manual__2025-03-04T18:46:35.938921+00:00, execution_date=20250304T184635, start_date=20250304T184642, end_date=20250304T184643
[2025-03-04T12:46:43.280-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:46:43.302-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:46:43.304-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
