[2025-02-27T13:05:03.802-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T13:05:04.147-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-27T13:05:04.288-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-27T13:05:04.289-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-27T13:05:05.289-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-20 00:00:00+00:00
[2025-02-27T13:05:05.332-0600] {standard_task_runner.py:72} INFO - Started process 43601 to run task
[2025-02-27T13:05:05.468-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-20T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpm4_a2n3m']
[2025-02-27T13:05:05.539-0600] {standard_task_runner.py:105} INFO - Job 7: Subtask SendMessage
[2025-02-27T13:06:50.807-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-02-27T13:06:51.386-0600] {job.py:229} INFO - Heartbeat recovered after 110.35 seconds
[2025-02-27T13:07:17.975-0600] {job.py:229} INFO - Heartbeat recovered after 27.47 seconds
[2025-02-27T13:07:18.451-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T00:00:00+00:00'
[2025-02-27T13:07:18.489-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T13:07:23.191-0600] {job.py:229} INFO - Heartbeat recovered after 20.62 seconds
[2025-02-27T13:12:18.730-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-02-27T13:12:19.791-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T13:12:19.808-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-20T00:00:00+00:00, execution_date=20250220T000000, start_date=20250227T190504, end_date=20250227T191219
[2025-02-27T13:12:20.170-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-27T13:12:20.324-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T13:12:20.327-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
