[2025-03-04T12:27:26.360-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:26.501-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.542-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.543-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:26.649-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-21 00:00:00+00:00
[2025-03-04T12:27:26.661-0600] {standard_task_runner.py:72} INFO - Started process 19653 to run task
[2025-03-04T12:27:26.679-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-21T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpgbxv39e_']
[2025-03-04T12:27:26.685-0600] {standard_task_runner.py:105} INFO - Job 2: Subtask SendMessage
[2025-03-04T12:27:27.027-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:28.746-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-21T00:00:00+00:00'
[2025-03-04T12:27:28.754-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:47.650-0600] {job.py:229} INFO - Heartbeat recovered after 50.24 seconds
[2025-03-04T12:29:08.276-0600] {job.py:229} INFO - Heartbeat recovered after 25.38 seconds
[2025-03-04T12:31:23.560-0600] {job.py:229} INFO - Heartbeat recovered after 58.10 seconds
[2025-03-04T12:32:17.005-0600] {job.py:229} INFO - Heartbeat recovered after 103.31 seconds
[2025-03-04T12:32:29.826-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:31.013-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:31.024-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-21T00:00:00+00:00, execution_date=20250221T000000, start_date=20250304T182726, end_date=20250304T183231
[2025-03-04T12:32:31.416-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:31.611-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:31.616-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
