[2025-03-03T13:14:24.281-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T13:14:24.315-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-03T19:14:14.292439+00:00 [queued]>
[2025-03-03T13:14:24.333-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-03T19:14:14.292439+00:00 [queued]>
[2025-03-03T13:14:24.334-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-03T13:14:24.362-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): StoreData> on 2025-03-03 19:14:14.292439+00:00
[2025-03-03T13:14:24.370-0600] {standard_task_runner.py:72} INFO - Started process 30794 to run task
[2025-03-03T13:14:24.375-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'StoreData', 'manual__2025-03-03T19:14:14.292439+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmp60kmutn5']
[2025-03-03T13:14:24.378-0600] {standard_task_runner.py:105} INFO - Job 66: Subtask StoreData
[2025-03-03T13:14:24.469-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.StoreData manual__2025-03-03T19:14:14.292439+00:00 [running]> on host IMNOTROY.
[2025-03-03T13:14:24.695-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='StoreData' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T19:14:14.292439+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T19:14:14.292439+00:00'
[2025-03-03T13:14:24.697-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T13:14:24.760-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-03T13:14:24.761-0600] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-03T13:14:24.762-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-03T13:14:24.764-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-03T13:14:24.765-0600] {__init__.py:150} INFO - plugin_name: mysql_native_password
[2025-03-03T13:14:24.769-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
[2025-03-03T13:14:24.830-0600] {dataEngineering.py:62} INFO - Data stored succesfully!
[2025-03-03T13:14:24.848-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T13:14:24.869-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T13:14:24.871-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=StoreData, run_id=manual__2025-03-03T19:14:14.292439+00:00, execution_date=20250303T191414, start_date=20250303T191424, end_date=20250303T191424
[2025-03-03T13:14:24.952-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T13:14:24.991-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T13:14:24.995-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
